# Generated by Django 4.2.3 on 2023-07-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='invoice',
            new_name='invoice_no',
        ),
    ]
